In [41]:
#import libraries
from numpy import array
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
import pandas as pd

In [42]:
#Reading file
df = pd.read_csv('/content/titanic.csv')

In [43]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [45]:
#Label and features
X = df[['Pclass','SibSp','Parch','Fare']]
Y = df.Survived

In [46]:
Y.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [47]:
X.head()

Pclass  SibSp  Parch     Fare
0       3      1      0   7.2500
1       1      1      0  71.2833
2       3      0      0   7.9250
3       1      1      0  53.1000
4       3      0      0   8.0500

In [48]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   SibSp   891 non-null    int64  
 2   Parch   891 non-null    int64  
 3   Fare    891 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 28.0 KB


In [49]:
#Test data and training data formation
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

# SVM

In [50]:
from sklearn import svm
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

from sklearn.model_selection import cross_val_score,KFold

model = svm.SVC()
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

print('Accuracy Score:\n',accuracy_score(Y_test, Y_pred))
print('Confusion Matrix:\n',confusion_matrix(Y_test, Y_pred))
print('Classification Report:\n',classification_report(Y_test,Y_pred))

kf=KFold(n_splits=5)
score=cross_val_score(model,X,Y,cv=kf)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Accuracy Score:
 0.6995515695067265
Confusion Matrix:
 [[131   7]
 [ 60  25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.95      0.80       138
           1       0.78      0.29      0.43        85

    accuracy                           0.70       223
   macro avg       0.73      0.62      0.61       223
weighted avg       0.72      0.70      0.66       223

Cross Validation Scores are [0.62011173 0.66853933 0.66853933 0.66292135 0.70786517]
Average Cross Validation score :0.6655953800765803


# Grid search to identify the best possible SVM model

### 'C'     :     [0.1, 1, 10, 100, 1000]
### 'gamma' :     [1, 0.1, 0.01, 0.001, 0.0001]
### 'kernel':     ['rbf'] 

In [51]:
parameters ={'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
     'criterion' : ['gini', 'entropy'],
     'n_estimators': [50,100,200,400,600]}

In [52]:
from sklearn.model_selection import ParameterGrid
param_size = ParameterGrid(parameters)
len(param_size)

100

In [53]:
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.619 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.612 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.612 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.617 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.617 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.619 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.612 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.612 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.609 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.617 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.627 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [54]:
# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=100, gamma=0.01)


In [55]:
grid_predictions = grid.predict(X_test)
  
# print classification report
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.72      0.87      0.79       138
           1       0.68      0.46      0.55        85

    accuracy                           0.71       223
   macro avg       0.70      0.66      0.67       223
weighted avg       0.71      0.71      0.70       223



In [56]:
#best possible SVM model using Random Search

from sklearn.model_selection import RandomizedSearchCV

random_search=RandomizedSearchCV(estimator = svm.SVC(), param_distributions=param_grid,verbose=2, n_jobs=-1,
                            n_iter=50)
random_result = random_search.fit(X_train, Y_train)
print('Best Score: ', random_result.best_score_*100)
print('Best Params: ', random_result.best_params_)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:296: UserWarning: The total space of parameters 25 is smaller than n_iter=50. Running 25 iterations. For exhaustive searches, use GridSearchCV.
  UserWarning,


Best Score:  70.21321961620468
Best Params:  {'kernel': 'rbf', 'gamma': 0.01, 'C': 100}


In [57]:

model_svc = SVC(kernel='rbf', C=100, gamma=0.01)
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)
print('Accuracy Score:\n',accuracy_score(Y_test, Y_pred))
print('Confusion Matrix:\n',confusion_matrix(Y_test, Y_pred))
print('Classification Report:\n',classification_report(Y_test,Y_pred))

Accuracy Score:
 0.6995515695067265
Confusion Matrix:
 [[131   7]
 [ 60  25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.95      0.80       138
           1       0.78      0.29      0.43        85

    accuracy                           0.70       223
   macro avg       0.73      0.62      0.61       223
weighted avg       0.72      0.70      0.66       223



In [58]:
#best possible SVM model using hyperopt

from hyperopt import tpe, hp, fmin, STATUS_OK,Trials

# define objective function

def hyperparameter_tuning(params):
    clf = SVC(**params)
    acc = cross_val_score(clf, X, Y,scoring="accuracy").mean()
    return {"loss": -acc, "status": STATUS_OK}

In [59]:


# Initialize trials object

param_grid = {
    "C": hp.choice("C", [0.1, 1, 10, 100, 1000]),
    "gamma": hp.choice("gamma", [1, 0.1, 0.01, 0.001, 0.0001]),
    "kernel": hp.choice("kernel", ['rbf']),
}

trials = Trials()

best = fmin(
    fn=hyperparameter_tuning,
    space = param_grid, 
    algo=tpe.suggest, 
    max_evals=50, 
    trials=trials
)

print("Best: {}".format(best))

100%|██████████| 50/50 [00:53<00:00,  1.07s/it, best loss: -0.7060134329295085]
Best: {'C': 4, 'gamma': 1, 'kernel': 0}


In [60]:

model_svc = SVC(kernel='rbf', C=1000, gamma=0.1)
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)
print('Accuracy Score:\n',accuracy_score(Y_test, Y_pred))
print('Confusion Matrix:\n',confusion_matrix(Y_test, Y_pred))
print('Classification Report:\n',classification_report(Y_test,Y_pred))




Accuracy Score:
 0.6995515695067265
Confusion Matrix:
 [[131   7]
 [ 60  25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.95      0.80       138
           1       0.78      0.29      0.43        85

    accuracy                           0.70       223
   macro avg       0.73      0.62      0.61       223
weighted avg       0.72      0.70      0.66       223



Submitted By: Ajuma Mohammed, AI-ML Aug22 Batch